/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "theme-bg": "var(--theme-bg)",
        "theme-surface": "var(--theme-surface)",
        "theme-surface-container": "var(--theme-surface-container)",
        "theme-border": "var(--theme-border)",
        "theme-text": "var(--theme-text)",
        "theme-text-muted": "var(--theme-text-muted)",
        "theme-accent": "var(--theme-accent)",
        "inverse-surface": "#213145",
        "inverse-primary": "#4ae176",
        "secondary-fixed-dim": "#c7c7bc",
        "surface-container-low": "#eff4ff",
        "on-surface-variant": "#3d4a3d",
        "secondary-fixed": "#e4e3d7",
        "on-primary-container": "#004b1e",
        "surface-variant": "#d3e4fe",
        "outline-variant": "#bccbb9",
        "on-tertiary": "#ffffff",
        "secondary-container": "#e4e3d7",
        "surface-container-highest": "#d3e4fe",
        "on-secondary-fixed-variant": "#46473f",
        "on-secondary": "#ffffff",
        "surface": "var(--theme-surface)",
        "primary-fixed-dim": "#4ae176",
        "tertiary-container": "#7ab8a0",
        "tertiary-fixed": "#b0f0d6",
        "outline": "var(--theme-border)",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#002117",
        "on-secondary-container": "#64655c",
        "tertiary": "#2b6954",
        "surface-dim": "#cbdbf5",
        "on-tertiary-fixed-variant": "#0b513d",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#1b1c15",
        "background": "var(--theme-bg)",
        "surface-container-high": "#dce9ff",
        "on-background": "#0b1c30",
        "tertiary-fixed-dim": "#95d3ba",
        "surface-container": "var(--theme-surface-container)",
        "on-error-container": "#93000a",
        "primary-container": "#22c55e",
        "inverse-on-surface": "#eaf1ff",
        "on-surface": "var(--theme-text)",
        "surface-tint": "#006e2f",
        "on-tertiary-container": "#004937",
        "on-primary-fixed": "#002109",
        "primary": "var(--theme-accent)",
        "surface-bright": "#f8f9ff",
        "secondary": "#5e5f56",
        "surface-container-lowest": "var(--theme-surface)",
        "primary-fixed": "#6bff8f",
        "on-primary-fixed-variant": "#005321",
        "on-primary": "#ffffff"
      },
      fontFamily: {
        "headline": ["Outfit", "Plus Jakarta Sans", "sans-serif"],
        "body": ["Outfit", "Plus Jakarta Sans", "sans-serif"],
        "label": ["Outfit", "Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
